### ISSUE TITLE
Rendering Issue with Mathematical Notation

### ISSUE THREAD

**Issue by AbhiTheModder** [dagmawibabi/ScholArxiv#11]
Hello,
First of all, I would like to express my gratitude for developing such an amazing app. I have been using it regularly and it has been a great help to me.

**Description:**
There's an issue with the rendering of mathematical notation in the titles of some research papers. [See Screenshots Below]

**Screenshots:**
![Screenshot_2024-08-20-07-05-21-437_com example arxiv](https://github.com/user-attachments/assets/4d918584-d25c-41b9-809e-84f2c3f4cb61)
![Screenshot_2024-08-20-07-13-13-537_com example arxiv](https://github.com/user-attachments/assets/a9ff43fd-462e-4adb-98c6-bdb154557749)
![Screenshot_2024-08-20-07-13-22-112_com example arxiv](https://github.com/user-attachments/assets/3e051e5e-29d0-487f-ae93-b2b36a962288)

**Expected Behavior:**
The mathematical notation in the title should be rendered correctly.

**Actual Behavior:**
The mathematical notation in the title is not being rendered correctly.

**Additional Context:**
I believe this issue is due to the use of special characters and LaTeX syntax, which may not be fully supported in the current rendering engine. maybe using packages like [flutter_tex](https://pub.dev/packages/flutter_tex) or [flutter_math_fork](https://pub.dev/packages/flutter_math_fork/versions) might fix it.

**Comment by dagmawibabi** [comment]
Thank you for your amazing contribution and for closing this issue.
