### ISSUE TITLE
[GRAPHICS] - BETTER LOGO

### ISSUE THREAD

**Issue by dagmawibabi** [dagmawibabi/ScholArxiv#23]
Would be fun to have an original contribution or the logo

**Comment by eyuelzero** [comment]
I love the current logo, so I've decided to just remaster it for better quality and file types. I also have ideas for the logo's animation. I'll contribute later today.

**Comment by dagmawibabi** [comment]
@eyuelzero great job, loving the vector format and the animation! 💯
