### ISSUE TITLE
Empty list when opening app

### ISSUE THREAD

**Issue by dagmawibabi** [dagmawibabi/ScholArxiv#24]
When opening the app and there are no suggested papers, the app should re-search and suggest

**Comment by dagmawibabi** [comment]
@eban12 wanna fix this?

**Comment by eban12** [comment]
I don't understand what you mean by if there are no suggested papers

**Comment by eban12** [comment]
Ah okay i think I understand what you mean. If the randomly picked topic doesn't have papers, the page would be empty. I will try to come up with something
