### ISSUE TITLE
How to Use it on MacOS Desktop or IOS iPhone?

### ISSUE THREAD

**Issue by jacklanda** [dagmawibabi/ScholArxiv#43]

**Comment by dagmawibabi** [comment]
Currently you'd have to come the repo and build from source since I don't have a developer account I couldn't publish it on the App store. But I'm working on a web version soon to be released so look out for that :) 

https://github.com/user-attachments/assets/6c6b68be-d2d6-4f6b-9214-7a05ebca8c38

**Comment by dagmawibabi** [comment]
@jacklanda please checkout ScholarXIV.com and let me know what you think of it :)
